# Generated by Django 2.2.1 on 2019-05-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summoner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBySummoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=128)),
                ('gameId', models.CharField(max_length=128)),
                ('champion', models.PositiveIntegerField()),
                ('platformId', models.CharField(max_length=128)),
                ('season', models.PositiveIntegerField()),
                ('queue', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=128)),
                ('timestamp', models.CharField(max_length=128)),
                ('summoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summoner.Summoner')),
            ],
        ),
    ]
