# Generated by Django 2.2.1 on 2019-05-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonId', models.PositiveIntegerField()),
                ('queueId', models.PositiveIntegerField()),
                ('gameId', models.CharField(max_length=128)),
                ('participantIdentities', models.CharField(max_length=128)),
                ('gameVersion', models.CharField(max_length=128)),
                ('platformId', models.CharField(max_length=128)),
                ('gameMode', models.CharField(max_length=128)),
                ('mapId', models.PositiveIntegerField()),
                ('gameType', models.CharField(max_length=128)),
                ('gameDuration', models.CharField(max_length=128)),
                ('gameCreation', models.CharField(max_length=128)),
            ],
        ),
    ]
