# Generated by Django 2.2.1 on 2019-06-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_participantstatsbymatch_statsbyparticipant_teamstatsbymatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='altarsCaptured',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='altarsNeutralized',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='nodeCapture',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='nodeCaptureAssist',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='nodeNeutralize',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='nodeNeutralizeAssist',
        ),
        migrations.RemoveField(
            model_name='statsbyparticipant',
            name='teamObjective',
        ),
    ]
