# Generated by Django 2.2.1 on 2019-06-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20190603_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantstatsbymatch',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
        migrations.AlterField(
            model_name='statsbyparticipant',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.ParticipantStatsByMatch'),
        ),
        migrations.AlterField(
            model_name='teamstatsbymatch',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
    ]
