# Generated by Django 2.2.1 on 2019-06-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20190603_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameByMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantByFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalGold', models.IntegerField()),
                ('teamScore', models.IntegerField()),
                ('participantId', models.IntegerField()),
                ('level', models.IntegerField()),
                ('currentGold', models.IntegerField()),
                ('minionsKilled', models.IntegerField()),
                ('dominionScore', models.IntegerField()),
                ('position', models.CharField(max_length=40)),
                ('xp', models.IntegerField()),
                ('jungleMinionsKilled', models.IntegerField()),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.FrameByMatch')),
            ],
        ),
        migrations.CreateModel(
            name='EventByFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=64)),
                ('towerType', models.CharField(max_length=64)),
                ('teamId', models.IntegerField()),
                ('ascendedType', models.CharField(max_length=64)),
                ('killerId', models.IntegerField()),
                ('levelUpType', models.CharField(max_length=64)),
                ('pointCaptured', models.CharField(max_length=64)),
                ('assistingParticipantIds', models.CharField(max_length=40)),
                ('wardType', models.CharField(max_length=64)),
                ('monsterType', models.CharField(max_length=64)),
                ('eType', models.CharField(max_length=64)),
                ('skillSlot', models.IntegerField()),
                ('victimId', models.IntegerField()),
                ('timestamp', models.CharField(max_length=128)),
                ('afterId', models.IntegerField()),
                ('monsterSubType', models.CharField(max_length=64)),
                ('laneType', models.CharField(max_length=64)),
                ('itemId', models.IntegerField()),
                ('participantId', models.IntegerField()),
                ('buildingType', models.CharField(max_length=64)),
                ('creatorId', models.IntegerField()),
                ('position', models.CharField(max_length=40)),
                ('beforeId', models.IntegerField()),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.FrameByMatch')),
            ],
        ),
    ]
