# Generated by Django 2.2.2 on 2019-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(max_length=50)),
                ('accountId', models.CharField(max_length=56)),
                ('leaguePoints', models.IntegerField(default=0)),
            ],
        ),
    ]
