# Generated by Django 2.2.1 on 2019-06-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='leaguePoints',
            field=models.IntegerField(default=0),
        ),
    ]
