# Generated by Django 2.2.1 on 2019-06-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nameId', models.CharField(max_length=56)),
                ('championId', models.IntegerField(unique=True)),
            ],
        ),
    ]
