# Generated by Django 2.2.1 on 2019-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='primaryTag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
